### ISSUE TITLE
-c -m are not working 

### ISSUE THREAD

**Issue by sadanyh** [m-popovic/hjerson#3]
Hi Thanks for the interesting tool and paper.

Could you please advise on the -e -c and -m commands. I have problems applying them
 
This is the traceback for the -m command

Traceback (most recent call last):
  File "hjerson.py", line 860, in <module>
    main()
  File "hjerson.py", line 762, in main
    write_html(args.html, args.html, args.hypothesis_additional, hypWords, bestWerHypAdd, hypErrorCats, "hyp")
  File "hjerson.py", line 236, in write_html
    htmltxt.write(font+words[nc]+addcat+closefont)
NameError: name 'htmltxt' is not defined

**Comment by m-popovic** [comment]
Did you give the name of the file after -m? 

For example
hjerson.py -R my_reference -H my_hypothesis -m my_html.html
